---
kind: pipeline
name: test

steps:
  - name: build
    image: python:2.7-slim
    environment:
      VIRTUAL_ENV: ".venv"
    commands:
      - apt-get update && apt-get -y install gcc libjpeg62-turbo-dev zlib1g-dev
      - export PATH="$VIRTUAL_ENV/bin:$PATH"
      - pip install virtualenv
      - virtualenv $VIRTUAL_ENV
      - python -m pip install -r requirements.txt

  - name: test
    image: python:2.7-slim
    environment:
      VIRTUAL_ENV: ".venv"
    commands:
      - apt-get update && apt-get -y install libjpeg62-turbo zlib1g
      - export PATH="$VIRTUAL_ENV/bin:$PATH"
      - ./manage.py check
      - ./manage.py test
